### ISSUE TITLE
Office 2021

### ISSUE THREAD

**Issue by sirinath** [microsoft/python-in-excel#12]
Please make this available for those with Office 2021 licenses too.

**Comment by macky360** [comment]
This will not be coming to Office 2021. Office 2021 is a point in time release, it's core value proposition is that the experience remains constant. As a result, we cannot backport features.

**Comment by sirinath** [comment]
But we are still under the support window. So I believe we should get updates until 2026.

**Comment by macky360** [comment]
Bug and security updates are included by not new features.

**Comment by keyur32** [comment]
Marking this issue as closed per note above.
