### ISSUE TITLE
Potential infinite loop bug with lists

### ISSUE THREAD

**Issue by b-gonzalez** [microsoft/python-in-excel#17]
Please see the screenshots below:

![image](https://github.com/microsoft/python-in-excel/assets/75147430/231f477c-fd7b-4ba0-924d-2559e616620f)

![image](https://github.com/microsoft/python-in-excel/assets/75147430/f728ea8d-cfe6-4750-9dbd-5525ba3bbf7a)

**Description:** 

Cell A1 contains code that references an instance of a list that's assigned to the variable `l`

Cells C1:C3 contain the values 1 through 3.

Cells D1:D3 reference `l` and append the values in cells C1:C3 to it

Cells F1:F3 reference the `l` variable and use the Excel Value option as the python object.

Cell F1 outputs the first value in variable `l` which is 1

Cell F2 outputs the first two values in variable `l` and spills. So the values it outputs are 1 and 2

If I keep F2 spilled but fill down to output F3, it looks like I get stuck in an infinite loop with the calculation engine constantly recalculating. Please see the screenshot below:

![image](https://github.com/microsoft/python-in-excel/assets/75147430/e769a247-89b3-4b4e-9469-e4c9baf81bb4)

![image](https://github.com/microsoft/python-in-excel/assets/75147430/db5e1cba-1fa6-4dbb-897d-9eb1bc7a5fe5)

Let me know if you have additional questions.

Thanks!

-Brian

**Comment by keyur32** [comment]
Thank you! We're taking a look.

**Comment by keyur32** [comment]
Believe this was fixed a while back. Closing but please re-open if needed.
