### ISSUE TITLE
Include nltk assets in conda env

### ISSUE THREAD

**Issue by ncalm** [microsoft/python-in-excel#23]
It would be great if we could have the deployed conda environment include useful nltk assets downloaded by default. 

e.g.
punkt
maxent_treebank_pos_tagger
average_perceptron_tagger
universal_tagset
vader_lexicon
stopwords
maxent_ne_chunker
etc

**Comment by keyur32** [comment]
thanks for logging this. Marking as 'enhancement' as this is under consideration.

**Comment by jflam** [comment]
This request is likely in the same bucket as enabling download of arbitrary conda and pip packages as well. The mechanism is likely the same - privileged operations to download the packages or data payloads prior to any user code executing in the environment.

**Comment by keyur32** [comment]
Updated. See https://support.microsoft.com/en-us/office/open-source-libraries-and-python-in-excel-c817c897-41db-40a1-b9f3-d5ffe6d1bf3e for details. Thx.

**Comment by davidanhip** [comment]
I know this is marked as fixed with the added libraries.  I'd love to get averaged_perceptron_tagger included for language tagging.  Should that be a new enhancement request?
