### ISSUE TITLE
Excel display value of set is #N/A

### ISSUE THREAD

**Issue by ncalm** [microsoft/python-in-excel#26]
These return a set object which can be printed and is intact, but the object can't be displayed in a cell:
```
set(pd.Series([1,2,3,4,5]))
set([1,2,3,4,5])
```

When trying to display in a cell, it shows #N/A. 

I would expect it to just display the set as a spilled array, similar to ndarray or series.

**Comment by keyur32** [comment]
Thank you for the report. Marking this as an enhancement so we can follow up on.

**Comment by keyur32** [comment]
Internal bug id: 8409804

**Comment by keyur32** [comment]
This is now fixed. Please reply back if you have any comments.
