### ISSUE TITLE
Improve plot handling

### ISSUE THREAD

**Issue by fzumstein** [microsoft/python-in-excel#30]
Currently, when returning a plot, you need to

* change it from object to values
* right-click, then select Picture in cell > Create reference
* change cell back to object as otherwise it's almost indistinguishable from an empty cell

Ideally, this should all happen automatically, or at least the Create Picture Reference should be available under the `Python Output` context menu, without having to change from object to values first.

**Comment by keyur32** [comment]
Thanks for the report (and sorry for the delay). We're thinking about this area, but no ETA.

**Comment by fzumstein** [comment]
This is now available via right click > "display plot over cells"
