### ISSUE TITLE
=AJ instead =PY

### ISSUE THREAD

**Issue by leandrobi** [microsoft/python-in-excel#31]
In my excel, is not appearing the function =PY, instead of that, to use de py function I need type =AJ function.
My excel is on brazillian portuguese version and I'm using the 365 beta insider.

Is it a wrong translation for the Portuguese versions or is there a way to fix it to use "=py" instead of "=aj"?

**Comment by keyur32** [comment]
Hi there, this is known issue we have with an incorrect localization in Portuguese. Can you please share the Excel version number under File > Account?

**Comment by keyur32** [comment]
Internal bug #8265741

**Comment by leandrobi** [comment]
@keyur32 , sure, here:
"Microsoft® Excel® para Microsoft 365 MSO (Versão 2310 Build 16.0.16907.20000) 64 bits "

**Comment by keyur32** [comment]
Hi, it appears is still active. We're still investigating.

**Comment by keyur32** [comment]
Hi folks, this should be fixed in version 17106. Please let us know if this is still happening.

**Comment by sergiorfoliveira** [comment]
It's still happening...

**Comment by keyur32** [comment]
Hi folks, can you let us know if you are still seeing this happening even with the latest version of the beta?

**Comment by sergiorfoliveira** [comment]
Still happening  :(

**Comment by keyur32** [comment]
What version are you seeing this under?

**Comment by sergiorfoliveira** [comment]
[image: image.png]

**Comment by keyur32** [comment]
Hey there, the image didn’t seem to come through. Can you please try again? Thanks

**Comment by sergiorfoliveira** [comment]
The image shows: Version 2301 (build 16026-20200).

**Comment by keyur32** [comment]
Believe this was already addressed. Please let me know if it is not the case.
