### ISSUE TITLE
Stuck on refresh when reopening a file that has both =STOCKHISTORY and xl()

### ISSUE THREAD

**Issue by fzumstein** [microsoft/python-in-excel#48]
See attached sample file `test.xlsx`. When you open it, cell `R9` is stuck on refreshing like this:

<img width="132" alt="Screenshot 2024-01-06 at 11 40 17 AM" src="https://github.com/microsoft/python-in-excel/assets/2265504/5d518e8e-757b-4e0c-96f8-48e3eea019f0">

The only thing that seems to "fix" it is to click on `Reset Runtime` (`Reset` doesn't work), then edit `R9` and hit `Ctrl+Enter`.

[test.xlsx](https://github.com/microsoft/python-in-excel/files/13849292/test.xlsx)

**Comment by keyur32** [comment]
Hi there, Thanks for the report. 

I'm unable to repro.  A few questions:
- Can you please send a frown or share your session id here (File > Account > About Excel >  Select Session ID and you can copy/paste it.
- Was there any workbooks with Python opened in the session?
- Do you have a repro from scratch or is it specific to this workbook?

**Comment by fzumstein** [comment]
My session ID Is `ED9EDDE5-6862-4BA3-B5B0-F9C1CD736851` and I tried it with the attached simplied book, which I created from scratch. Got the same issue.
[refresh_issue.xlsx](https://github.com/microsoft/python-in-excel/files/13864021/refresh_issue.xlsx)

**Comment by keyur32** [comment]
This should now be fixed. Can you please check to see if it's still happening on your end?

**Comment by fzumstein** [comment]
This works for me for the second file in this thread (refresh_issue.xlsx), but for the first one (test.xlsx), I need to hit `Ctrl+Alt+F9` to make this work (no reset anymore though).

**Comment by fzumstein** [comment]
There's actually something else going on, see this new test file: when there's more than one PY cells, the 2nd cell fails with a `NameError`, see screenshot. When you hit `Ctrl+Alt+F9`, everything works properly again.

<img width="1918" alt="Screenshot 2024-01-29 at 9 44 47 PM" src="https://github.com/microsoft/python-in-excel/assets/2265504/ca12d10c-dd88-4661-85b7-71eb623c91e8">

[python_error.xlsx](https://github.com/microsoft/python-in-excel/files/14089418/python_error.xlsx)

**Comment by keyur32** [comment]
I think this is also fixed now, closing but feel free to recactivate if you repro
