### ISSUE TITLE
Installed Beta Channel but "py" function isn't available

### ISSUE THREAD

**Issue by paultiq** [microsoft/python-in-excel#5]
It appears that I have the correct Excel version, according to the release notes: 
![image](https://github.com/microsoft/python-in-excel/assets/104510378/03283ff2-0171-414e-9643-2365e668c2f9)

[Release notes](https://techcommunity.microsoft.com/t5/excel-blog/announcing-python-in-excel-combining-the-power-of-python-and-the/ba-p/3893439) say "This feature will roll out to Excel for Windows first, starting with build 16.0.16818.20000, " is required, which is what I have.

I was able to add Python to my Ribbon: 
![image](https://github.com/microsoft/python-in-excel/assets/104510378/3f6bdb8a-b300-4686-b767-0b2a59614afd)

And the Try Excel sidebar shows up: 
![image](https://github.com/microsoft/python-in-excel/assets/104510378/b336afa4-2c66-4ce7-818f-9f3215c5d1f5)

But, =py(...) doesn't work, `py` is an unknown name. And clicking Insert Python from ribbon does nothing.

**Comment by ccyet** [comment]
same as you, its not that public version maybe

**Comment by BSalita** [comment]
Same. Just guessing, I'm wondering if it's an inability to connect to the cloud as opposed to a local software issue. We'll probably soon know.

**Comment by ielcoro** [comment]
Same here

**Comment by jflam** [comment]
Hey Folks,

There is a bug where you can enable the ribbon buttons for Python in Excel without having complete access to the feature. We are actively working on a fix for this issue and apologize for any confusion this has caused. Enabling the ribbon button will not give you access to Python in Excel. 

New features for Excel are rolled out gradually to each audience so we can monitor and address issues before they affect larger audiences. We are currently not yet available for 100% of users on the Beta Channel - so only a subset of users in this audience currently have access to the feature. Stay tuned for more information and [sign up here](https://developer.microsoft.com/en-us/microsoft-365/profile?source=python) to be notified about future availability.

**Comment by jessxahmet** [comment]
Thanks for the update @jflam! This hasn't been made clear in all of the posts surrounding accessing this feature. Do we have an ETA as to when this may be rolled out to all users on the beta channel? I have signed up to the developer program too! Thanks in advance! 

> Hey Folks,
> 
> There is a bug where you can enable the ribbon buttons for Python in Excel without having complete access to the feature. We are actively working on a fix for this issue and apologize for any confusion this has caused. Enabling the ribbon button will not give you access to Python in Excel.
> 
> New features for Excel are rolled out gradually to each audience so we can monitor and address issues before they affect larger audiences. We are currently not yet available for 100% of users on the Beta Channel - so only a subset of users in this audience currently have access to the feature. Stay tuned for more information and [sign up here](https://developer.microsoft.com/en-us/microsoft-365/profile?source=python) to be notified about future availability.

**Comment by ilovefreesw** [comment]
Same..

![image](https://github.com/microsoft/python-in-excel/assets/77317006/d9a3053b-3c26-45d1-bb4e-08fff0b6b475)

I don't even have the ribbon option :{}

**Comment by paultiq** [comment]
Got it this week, looks like this is all good. Thank you.
