### ISSUE TITLE
Excel slows down and shows #BUSY! when switching output mode while a Python formula is calculating

### ISSUE THREAD

**Issue by keyur32** [microsoft/python-in-excel#50]
Logging this current issue for visibility for a recent bug. Will update once fixed.

If you hit this, would suggest switching to be in Partial or Manual re-calc for now.

**Comment by keyur32** [comment]
This should now be fixed.

**Comment by gasernag** [comment]
I am testing Python for Excel with a sheet that has only 3 cells an two short lines of simple Python code and it takes 15 seconds to switch modes.

**Comment by shaofengzhu** [comment]
Would you please paste sessionId? Please access "File" -> "Account" -> "About Excel", then copy the "Session ID".

**Comment by keyur32** [comment]
Thank you for the report @gasernag. We've investigated and a fix is rolling out to this issue.

**Comment by gasernag** [comment]
Thank you.

Professor Serna
786-290-9100
***@***.***
www.professorserna.com
