### ISSUE TITLE
Moving PY cells doesn't properly recalculate

### ISSUE THREAD

**Issue by fzumstein** [microsoft/python-in-excel#53]
* Put a PY cell into A1 and A2.

  `A1`: `hello = "hello"`
  `A2`: `hello`

  This works as expected.

* Now move `A1` to `A3`: no error is being shown, which is incorrect as `hello` isn't defined yet in `A2`. 

* Hit `Ctrl+Alt+F9`: now the error shows up properly in `A2` (`NameError: name 'hello' is not defined`).

**Comment by keyur32** [comment]
Internal bug: 8832494

**Comment by keyur32** [comment]
Can you see if this still repros for you?  We are no longer able to repro (and I'm not personally sure I wasn't in partial or manual mode when I did initially repro :))

**Comment by fzumstein** [comment]
Yes, still able to repro with Automatic calculation on Microsoft® Excel® for Microsoft 365 MSO (Version 2404 Build 16.0.17514.20000) 64-bit, Session ID: 992DD573-3174-48CA-B3A1-53ABFED91311

**Comment by keyur32** [comment]
Delay on my part, but we weren't able to repro this internally, shortly after posting it, so marking as fixed. Verified in the latest build it does not repro either.

**Comment by fzumstein** [comment]
yup, now it works correctly over here, too! thanks!
