### ISSUE TITLE
Python in Excel not working in version 17404.20000

### ISSUE THREAD

**Issue by 666dsa666** [microsoft/python-in-excel#55]
Hello,
A user has been using Python in Excel since November but the option disappeared and now states he got to register to use the functionality.

![image](https://github.com/microsoft/python-in-excel/assets/11072018/b91df769-431d-45e2-a5a0-971d282bb802)

Version is last beta build - 2403, 17404.20000

**Comment by keyur32** [comment]
hi sorry for the delay. What happens whey the click "Try Preview" which I think is titled "En savoir plus" in the screenshot above?

**Comment by 666dsa666** [comment]
> hi sorry for the delay. What happens whey the click "Try Preview" which I think is titled "En savoir plus" in the screenshot above?

Hello,
This does sent us to the documentation about preview

**Comment by keyur32** [comment]
Thanks. following up with you offline.
