### ISSUE TITLE
File broken by being edited in Current Channel non-beta Excel version

### ISSUE THREAD

**Issue by santiago-afonso** [microsoft/python-in-excel#56]
Hello. I've been working with my team on a Python-infused workbook. Two of the team have the beta channel Excel with Python enabled, the third has a Current Channel non-Python Windows Excel version. When the last one edits the file it becomes corrupted.

Afterwards, if one of the Python-enabled users opens the file, we get an this error on open: "We found a problem with some content... Do you want us to try to recover as much as we can?" The XML log generated points to the Python-infused worksheet. The non-Python user didn't edit this worksheet (Python code is confined to that single worksheet). The recovered file has the output Python objects/Python card in the appropriate cells, but the Python code is missing. Ie the card is there but no Python code as can be seen on the screenshot (Python code should be shown in the formula bar).

![image](https://github.com/microsoft/python-in-excel/assets/13853688/2bb8511b-b757-47ba-a816-1010b3e870aa)

This is extremely problematic for collaboration, ie would preclude us for using Python if this behaviour (which we understand is unexpected) were to continue in the future.

**Comment by keyur32** [comment]
Hi @osnofas, Thank you for reporting this issue.  We're currently working on enabling Python in Excel to more users in the coming months.  For now, would recommend coauthoring on "Python aware" versions, and we'll report back once this is resolved.

**Comment by keyur32** [comment]
Hi @osnofas, can you also confirm if the 3rd user on the Current Channel was trying to modify the Python formula, or something else in the workbook when they hit this corruption?  Thanks!

**Comment by osnofas** [comment]
> Hi @osnofas, can you also confirm if the 3rd user on the Current Channel was trying to modify the Python formula, or something else in the workbook when they hit this corruption? Thanks!

We keep all of the Python code in a single worksheet. The 3rd user didn't edit that worksheet at all. (Sorry for the delay - I was OOO.)

**Comment by keyur32** [comment]
Hi there, this should be fixed now that Python  is available in the current channel. Please let us know if you continue to see this issue.
