### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Tiberriver256** [microsoft/python-in-excel#58]
Hello 👋 

Could this feature and its rollout be added to the Microsoft 365 Roadmap?

https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Excel

**Comment by keyur32** [comment]
Hi there, yes this has been added to the roadmap. We will also add updates for upcoming enhancements (I.e. Mac and Web support which will come later) once we have clarity on dates.
