### ISSUE TITLE
Python in Excel Availability (cannot get to work)

### ISSUE THREAD

**Issue by drew-DMCBIO** [microsoft/python-in-excel#63]
Hi All! Not sure if this is the best place to post this, but myself and my organization manager are having a hard time figuring out why we can't access the python in excel functionality now that it seems more widely rolled out. On Windows 11 Business Excel version 2407 (build 17830.20210) and the Beta Insider channel. Have tried all the common troubleshooting that we've found online. We are debating paying for the premium compute add on to see if that will trigger our version of excel to update for this functionality. Do we just need to keep waiting or is there something we can do?

**Comment by keyur32** [comment]
Hi @drew-DMCBIO, can you please send some feedback internally if you haven't already via File> Send Feedback? This will allow us collect some logs to see what you are not seeing it on Beta channel.

**Comment by stonebig** [comment]
It's in "current" channel but not yet on "monthly entreprise" , sadly

**Comment by keyur32** [comment]
Hey there, it is now available on the "Monthly Enterprise Channel". 

@drew-DMCBIO - were you able to see why you were unable to see Python? Would recommend re-running setup by logging into Office.com and clicking "Install Office".

**Comment by drew-DMCBIO** [comment]
Thanks for following up! Unfortunately, it still will not work for me. I am fully updated (Version 2408 17928.20216), re-installed Office, and can see the Insert Python button under Formulas now. However, when I try to use it I get the following message about not having an active license.

***@***.***

I even have the paid Python Add-On associated with my account and I still get that error. Is there another institutional setting that could be blocking the functionality?

***@***.***

Thanks!!
Drew DeLorenzo

**Comment by keyur32** [comment]
Bummer. Let's try to setup a debug call.  Can you send feedback first in the application and put this github issue in the notes please, along with checking the box that will allow us to contact you?

**Comment by drew-DMCBIO** [comment]
Thanks for the quick reply! I just submitted the feedback through the Excel application. Appreciate having a debug call, hopefully that will get it resolved. Thanks Keyur!

Drew DeLorenzo

**Comment by keyur32** [comment]
We were able to resolve this offline (reinstallation of Office fixed it). For any future updates, we'll keep updating this article on availability: https://support.microsoft.com/en-us/office/python-in-excel-availability-781383e6-86b9-4156-84fb-93e786f7cab0
