### ISSUE TITLE
in the future, could it work on a WASM Python instead of a Cloud Python ?

### ISSUE THREAD

**Issue by stonebig** [microsoft/python-in-excel#65]
If it could work on a WASM Python instead of a Cloud Python, all things being equal:
- we may be twice slower
- but it may be less a stress on Datacenters, or a stress of unknown timing on users wanting to run something very cpu intensive

**Comment by salabim** [comment]
That's available!
And it is called Anaconda Code.
And with my anacondacode module running arbritrary length code is possible as well!

**Comment by keyur32** [comment]
Yes, you can use Anaconda code for it. We are always evaluating WASM, but do not yet have any plans to support it at this time.
