### ISSUE TITLE
Wasm and duckdb dream

### ISSUE THREAD

**Issue by stonebig** [microsoft/python-in-excel#67]
For my use case, sql computations, dream is:
- having for free the wasm version,
- having duckdb
- having the cloud version with multi-thread 8x or more AI

That would make:
- faster popularity and less electricity 
- 2x speed-up and less electricity
- 10x speed-up and less electricity and reactivity and a joy for business

**Comment by keyur32** [comment]
Thanks for the suggestion. We don't have any immediate plans for WASM, and we would recommend use PowerQuery in Excel to connect to the SQL data sources: https://support.microsoft.com/en-us/office/use-power-query-to-import-data-for-python-in-excel-028dbcd4-76c5-4aa4-831d-0e211fefc0a2. 

We don't have any plans to support duckdb either, given network access is disallowed for security. We'd also be concerned about users putting authentication information and connection information in their python code in the workbook.
